FROM node

WORKDIR /app

COPY ./package.json /app/package.json

COPY ./package-lock.json /app/package-lock.json

RUN npm install

COPY ./public /app/public

COPY ./src /app/src

EXPOSE 3000

RUN npm run build

WORKDIR /app/build

CMD ["npx", "serve", "-s", "-l", "3000"]