services:
  languageapp:
    environment:
    - PYTHONUNBUFFERED=1 # this is so that print statements are shown in docker container logs
    build:
      context: ./backend
    ports: 
      - "5000:5000"
      - "5678:5678"
      #- "8888:8888"
    volumes:
       - "./backend/notebook:/app/notebook"
    #command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m pytest
    #command: pytest
    #command: jupyter-notebook --ip 0.0.0.0 --no-browser --allow-root
    networks:
      - backend
    depends_on:
      - languageapp-db
      - languageapp-db-test
  languageapp-db:
    build: 
      context: ./db
    environment:
      POSTGRES_USER: languageapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: languageapp
    volumes:
      - ${HOME}/languageappdata:/var/lib/postgresql/data
    networks:
      - backend
  languageapp-db-test:
    build: 
      context: ./db
    environment:
      POSTGRES_USER: languageapptest
      POSTGRES_PASSWORD: passwordtest
      POSTGRES_DB: languageapptest
    networks:
      - backend
  languageapp-frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/public:/app/public"
    networks:
      - frontend
networks:
  frontend:
  backend:

