services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile.prod
    ports:
      - 1337:80
    depends_on:
      - languageapp
    networks:
      - backend
  nginx-frontend:
    restart: always
    build:
      context: ./nginx_frontend
      dockerfile: ./Dockerfile.prod
    ports:
      - 1336:80
    depends_on:
      - languageapp
    networks:
      - frontend
  languageapp:
    restart: always
    environment:
    - PYTHONUNBUFFERED=1 # this is so that print statements are shown in docker container logs
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    expose: 
      - 5000
    networks:
      - backend
    depends_on:
      - languageapp-db
  languageapp-db:
    restart: always
    build: 
      context: ./db
    environment:
      POSTGRES_USER: languageapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: languageapp
    volumes:
      - ${HOME}/languageappdata2:/var/lib/postgresql/data
    networks:
      - backend
  languageapp-frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    volumes:
      - "./frontend/src:/app/src"
    networks:
      - frontend

networks:
  backend:
  frontend:


