version: "3"
services:
  languageapp:
    environment:
    - PYTHONUNBUFFERED=1 # this is so that print statements are shown in docker container logs
    build:
      context: ./backend
    ports: 
      - "5000:5000"
      - "5678:5678"
      - "8888:8888"
    volumes:
      - "./backend/notebook:/app/notebook"
    #command: python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m pytest
    command: pytest
    #command: jupyter-notebook --ip 0.0.0.0 --no-browser --allow-root
    depends_on:
      - languageapp-db
      - languageapp-db-test
  ml:
    environment:
    - PYTHONUNBUFFERED=1 # this is so that print statements are shown in docker container logs
    build:
      context: ./ml
    ports: 
      - "8888:8888"
    volumes:
      - "./ml/notebook:/ml/notebook"
    command: pytest
    #command: jupyter-notebook --ip 0.0.0.0 --no-browser --allow-root
    depends_on:
      - languageapp-db
      - languageapp-db-test
  languageapp-db:
    build: 
      context: ./db
    environment:
      POSTGRES_USER: languageapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: languageapp
    volumes:
      - /home/medaphor/languageappdata:/var/lib/postgresql/data
  languageapp-db-test:
    build: 
      context: ./db
    environment:
      POSTGRES_USER: languageapptest
      POSTGRES_PASSWORD: passwordtest
      POSTGRES_DB: languageapptest
  languageapp-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"

